title: Psychtoolbox-3
url: http://towolf.github.com
permalink: pretty
pygments: true
markdown: kramdown

kramdown:
  auto_ids: false
  toc_levels: 1..5
  use_coderay: true
  hard_wrap: true

# redcarpet:
#     extensions: ["no_intra_emphasis", "fenced_code_blocks", "strikethrough", "autolink",
#                  "tables", "with_toc_data", "space_after_headers", "superscript"]

# rdiscount:
#   extensions: [smart, generate_toc]
#   toc_token: "{:toc}"

# google_analytics:
#   account: UA-XXXXX-X
